services:
  - type: web
    name: our-meals
    env: docker
    dockerfilePath: ./app.dockerfile
    dockerContext: .
    targetPort: 3000
    numInstances: 1
    healthCheckPath: /
    region: singapore
    domains: dev.ourmeals.online
    envVars:
      - key: DJANGO_DEBUG
        value: "0"
      - key: DJANGO_ALLOWED_HOSTS
        value: dev.ourmeals.online
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@ourmeals.online
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: our-meals-db
          property: connectionString
    buildCommand: docker build -t our-meals --target production .
    startCommand: >
      /bin/sh -c '
      python manage.py migrate &&
      python manage.py createsuperuser --noinput || true &&
      gunicorn ourmeals.wsgi:application --bind 0.0.0.0:3000 --workers 3
      '

databases:
  - name: our-meals-db
    databaseName: our_meals
    plan: free
    ipAllowList: [] # only allow internal connections
