# Generated by Django 5.1.4 on 2024-12-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
