# Generated by Django 5.1.4 on 2024-12-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_meal_meal_plan_alter_mealplan_shareable_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='grocery_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
