# Generated by Django 5.1.4 on 2024-12-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_mealplan_grocery_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='grocery_list_instruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
